<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7NY0woR\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7NY0woR/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container7NY0woR.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container7NY0woR\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container7NY0woR\App_KernelProdContainer([
    'container.build_hash' => '7NY0woR',
    'container.build_id' => '963f939e',
    'container.build_time' => 1701187291,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7NY0woR');
