<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_jogawmarkach_homepage' => [[], ['_controller' => 'App\\Controller\\JogaWMarkachController::homepage'], [], [['text', '/']], [], [], []],
];
