<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGXpywDN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGXpywDN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGXpywDN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGXpywDN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGXpywDN\App_KernelDevDebugContainer([
    'container.build_hash' => 'GXpywDN',
    'container.build_id' => '6329c54f',
    'container.build_time' => 1701439992,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGXpywDN');
