<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.9a71ee5d.js',
                '/build/449.97c7902b.js',
                '/build/app.605ee21d.js',
            ],
            'css' => [
                '/build/449.75d150a2.css',
                '/build/app.c49fa2c1.css',
            ],
        ],
    ],
],

]];
